runtime: python310  # Gunakan versi Python yang sesuai (Python 3.10)
entrypoint: gunicorn -b :$PORT app:app  # Gunakan gunicorn untuk menjalankan aplikasi

env_variables:
  FLASK_ENV: 'production'

handlers:
  - url: /static
    static_dir: static  # Gunakan folder 'static' untuk file statis seperti CSS, JS, dll.
  - url: /.*
    script: auto  # Semua request akan diteruskan ke Flask
